# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import monitor_pb2 as monitor__pb2 # pyright: ignore[reportMissingImports]

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in monitor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SystemMonitorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemStats = channel.unary_unary(
                '/monitor.SystemMonitor/GetSystemStats',
                request_serializer=monitor__pb2.SystemRequest.SerializeToString,
                response_deserializer=monitor__pb2.SystemStats.FromString,
                _registered_method=True)
        self.GetProcessStats = channel.unary_unary(
                '/monitor.SystemMonitor/GetProcessStats',
                request_serializer=monitor__pb2.ProcessRequest.SerializeToString,
                response_deserializer=monitor__pb2.ProcessStatsList.FromString,
                _registered_method=True)


class SystemMonitorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSystemStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystemStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStats,
                    request_deserializer=monitor__pb2.SystemRequest.FromString,
                    response_serializer=monitor__pb2.SystemStats.SerializeToString,
            ),
            'GetProcessStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessStats,
                    request_deserializer=monitor__pb2.ProcessRequest.FromString,
                    response_serializer=monitor__pb2.ProcessStatsList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monitor.SystemMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('monitor.SystemMonitor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemMonitor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSystemStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitor.SystemMonitor/GetSystemStats',
            monitor__pb2.SystemRequest.SerializeToString,
            monitor__pb2.SystemStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitor.SystemMonitor/GetProcessStats',
            monitor__pb2.ProcessRequest.SerializeToString,
            monitor__pb2.ProcessStatsList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
