# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monitor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmonitor.proto\x12\x07monitor\"%\n\rSystemRequest\x12\x14\n\x0cmachine_name\x18\x01 \x01(\t\"\xa2\x01\n\x0bSystemStats\x12\x11\n\ttotal_cpu\x18\x01 \x01(\x02\x12\x16\n\x0etotal_ram_used\x18\x02 \x01(\x02\x12\x11\n\ttotal_ram\x18\x03 \x01(\x02\x12\x15\n\rtotal_disk_io\x18\x04 \x01(\x02\x12\x12\n\ntotal_read\x18\x05 \x01(\x02\x12\x13\n\x0btotal_write\x18\x06 \x01(\x02\x12\x15\n\rlogical_cores\x18\x07 \x01(\x05\"\'\n\x0eProcessRequest\x12\x15\n\rprocess_names\x18\x01 \x03(\t\"\x80\x01\n\x0bProcessStat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07running\x18\x02 \x01(\x08\x12\x0b\n\x03\x63pu\x18\x03 \x01(\x02\x12\x11\n\tmemory_mb\x18\x04 \x01(\x02\x12\x0f\n\x07\x64isk_io\x18\x05 \x01(\x02\x12\x0f\n\x07read_mb\x18\x06 \x01(\x02\x12\x10\n\x08write_mb\x18\x07 \x01(\x02\";\n\x10ProcessStatsList\x12\'\n\tprocesses\x18\x01 \x03(\x0b\x32\x14.monitor.ProcessStat2\x96\x01\n\rSystemMonitor\x12>\n\x0eGetSystemStats\x12\x16.monitor.SystemRequest\x1a\x14.monitor.SystemStats\x12\x45\n\x0fGetProcessStats\x12\x17.monitor.ProcessRequest\x1a\x19.monitor.ProcessStatsListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMREQUEST']._serialized_start=26
  _globals['_SYSTEMREQUEST']._serialized_end=63
  _globals['_SYSTEMSTATS']._serialized_start=66
  _globals['_SYSTEMSTATS']._serialized_end=228
  _globals['_PROCESSREQUEST']._serialized_start=230
  _globals['_PROCESSREQUEST']._serialized_end=269
  _globals['_PROCESSSTAT']._serialized_start=272
  _globals['_PROCESSSTAT']._serialized_end=400
  _globals['_PROCESSSTATSLIST']._serialized_start=402
  _globals['_PROCESSSTATSLIST']._serialized_end=461
  _globals['_SYSTEMMONITOR']._serialized_start=464
  _globals['_SYSTEMMONITOR']._serialized_end=614
# @@protoc_insertion_point(module_scope)
